In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/accident_prediction_india.csv")

In [57]:
State_Name = df["State Name"].to_numpy()
print(State_Name)

['Jammu and Kashmir' 'Uttar Pradesh' 'Chhattisgarh' ... 'Meghalaya'
 'Meghalaya' 'Arunachal Pradesh']


In [58]:
city_name = df["City Name"].to_numpy()
print(city_name)

['Unknown' 'Lucknow' 'Unknown' ... 'Unknown' 'Unknown' 'Unknown']


In [59]:
year = df["Year"].to_numpy()
print(year)

[2021 2018 2023 ... 2021 2023 2020]


In [60]:
month = df["Month"].to_numpy()
print(month)

['May' 'January' 'May' ... 'January' 'June' 'September']


In [61]:
day_of_week = df["Day of Week"].to_numpy()
print(day_of_week)

['Monday' 'Wednesday' 'Wednesday' ... 'Thursday' 'Sunday' 'Monday']


In [62]:
time_of_day = df["Time of Day"].to_numpy()
print(time_of_day)

['1:46' '21:30' '5:37' ... '19:34' '20:54' '7:19']


In [63]:
accident_severity = df["Accident Severity"].to_numpy()
print(accident_severity)

['Serious' 'Minor' 'Minor' ... 'Minor' 'Fatal' 'Fatal']


In [64]:
Number_of_vehicles_involved = df["Number of Vehicles Involved"].to_numpy()
print(Number_of_vehicles_involved)

[5 5 5 ... 2 1 5]


In [65]:
number_of_casualties = df["Number of Casualties"].to_numpy()
print(number_of_casualties)

[0 5 6 ... 8 9 1]


In [66]:
number_of_fatalities = df["Number of Fatalities"].to_numpy()
print(number_of_fatalities)

[4 4 5 ... 5 2 3]


In [67]:
weather_conditions = df["Weather Conditions"].to_numpy()
print(weather_conditions)

['Hazy' 'Hazy' 'Foggy' ... 'Rainy' 'Stormy' 'Hazy']


In [68]:
road_type = df["Road Type"].to_numpy()
print(road_type)

['National Highway' 'Urban Road' 'National Highway' ... 'National Highway'
 'Urban Road' 'National Highway']


In [69]:
road_condition = df["Road Condition"].to_numpy()
print(road_condition)

['Wet' 'Dry' 'Under Construction' ... 'Dry' 'Under Construction'
 'Under Construction']


In [70]:
lighting_condition = df["Lighting Conditions"].to_numpy()
print(lighting_condition)

['Dark' 'Dusk' 'Dawn' ... 'Dark' 'Daylight' 'Daylight']


In [71]:
traffic_control_presence = df["Traffic Control Presence"].to_numpy()
print(traffic_control_presence)


['Signs' 'Signs' 'Signs' ... 'Signs' 'Signs' nan]


In [72]:
speed_limit = df["Speed Limit (km/h)"].to_numpy()
print(speed_limit)

[ 61  92 120 ...  47  60  40]


In [73]:
Driver_age = df["Driver Age"].to_numpy()
print(Driver_age)

[66 60 26 ... 57 28 66]


In [74]:
Driver_Gender = df["Driver Gender"].to_numpy()
print(Driver_Gender)

['Male' 'Male' 'Female' ... 'Female' 'Female' 'Male']


In [75]:
Driver_license_status = df["Driver License Status"].to_numpy()
print(Driver_license_status)

[nan nan nan ... 'Valid' 'Expired' nan]


In [76]:
Alcohol_involvement = df["Alcohol Involvement"].to_numpy()
print(Alcohol_involvement)

['Yes' 'Yes' 'No' ... 'Yes' 'Yes' 'Yes']


In [77]:
accident_location_Details= df["Accident Location Details"].to_numpy()
print(accident_location_Details)

['Curve' 'Straight Road' 'Bridge' ... 'Intersection' 'Bridge' 'Bridge']


In [123]:
weather_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/accident_prediction_india.csv')
print("Historical weather data loaded successfully.")
print(weather_df.head())

Historical weather data loaded successfully.
          State Name City Name  Year    Month Day of Week Time of Day  \
0  Jammu and Kashmir   Unknown  2021      May      Monday        1:46   
1      Uttar Pradesh   Lucknow  2018  January   Wednesday       21:30   
2       Chhattisgarh   Unknown  2023      May   Wednesday        5:37   
3      Uttar Pradesh   Lucknow  2020     June    Saturday        0:31   
4             Sikkim   Unknown  2021   August    Thursday       11:21   

  Accident Severity  Number of Vehicles Involved Vehicle Type Involved  \
0           Serious                            5                 Cycle   
1             Minor                            5                 Truck   
2             Minor                            5            Pedestrian   
3             Minor                            3                   Bus   
4             Minor                            5                 Cycle   

   Number of Casualties  ...         Road Type      Road Condition  \
0

In [120]:
try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.
An empty DataFrame named `weather_df` has been created to prevent subsequent errors.


In [121]:
try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")


Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.
An empty DataFrame named `weather_df` has been created to prevent subsequent errors.


In [122]:
try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.
An empty DataFrame named `weather_df` has been created to prevent subsequent errors.


In [124]:
try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.
An empty DataFrame named `weather_df` has been created to prevent subsequent errors.


In [125]:
print("Shape of weather_df:", weather_df.shape)
print("\nInfo of weather_df:")
weather_df.info()
print("\nHead of weather_df:")
print(weather_df.head())
print("\nMissing values in weather_df:")
print(weather_df.isnull().sum())

Shape of weather_df: (0, 0)

Info of weather_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

Head of weather_df:
Empty DataFrame
Columns: []
Index: []

Missing values in weather_df:
Series([], dtype: float64)


In [126]:
print("\nDescriptive statistics for numerical columns:")
print(weather_df.describe())

print("\nUnique values and counts for categorical columns:")
for column in weather_df.select_dtypes(include=['object', 'category']).columns:
    print(f"\nColumn: {column}")
    print("Unique Values:", weather_df[column].unique())
    print("Value Counts:\n", weather_df[column].value_counts())



Descriptive statistics for numerical columns:


ValueError: Cannot describe a DataFrame without columns

In [127]:
if weather_df.empty:
    print("weather_df is empty. Cannot generate descriptive statistics or categorical column analysis.")
else:
    print("\nDescriptive statistics for numerical columns:")
    print(weather_df.describe())

    print("\nUnique values and counts for categorical columns:")
    for column in weather_df.select_dtypes(include=['object', 'category']).columns:
        print(f"\nColumn: {column}")
        print("Unique Values:", weather_df[column].unique())
        print("Value Counts:\n", weather_df[column].value_counts())

weather_df is empty. Cannot generate descriptive statistics or categorical column analysis.


In [128]:
import matplotlib.pyplot as plt
import seaborn as sns

if weather_df.empty:
    print("weather_df is empty. Cannot generate a histogram for temperature distribution.")
else:
    # Assuming 'Temperature' column exists if weather_df was not empty
    if 'Temperature' in weather_df.columns:
        plt.figure(figsize=(10, 6))
        sns.histplot(weather_df['Temperature'], kde=True)
        plt.title('Distribution of Temperature Values')
        plt.xlabel('Temperature')
        plt.ylabel('Frequency')
        plt.grid(True)
        plt.show()
    else:
        print("The 'Temperature' column is not found in weather_df.")

weather_df is empty. Cannot generate a histogram for temperature distribution.


In [129]:
import matplotlib.pyplot as plt
import seaborn as sns

if weather_df.empty:
    print("weather_df is empty. Cannot generate a scatter plot for Temperature vs. Humidity.")
else:
    if 'Temperature' in weather_df.columns and 'Humidity' in weather_df.columns:
        plt.figure(figsize=(10, 6))
        sns.scatterplot(x=weather_df['Temperature'], y=weather_df['Humidity'])
        plt.title('Temperature vs. Humidity Relationship')
        plt.xlabel('Temperature')
        plt.ylabel('Humidity')
        plt.grid(True)
        plt.show()
    else:
        missing_cols = []
        if 'Temperature' not in weather_df.columns:
            missing_cols.append('Temperature')
        if 'Humidity' not in weather_df.columns:
            missing_cols.append('Humidity')
        print(f"The following required column(s) were not found in weather_df: {', '.join(missing_cols)}.")

weather_df is empty. Cannot generate a scatter plot for Temperature vs. Humidity.


In [130]:
import matplotlib.pyplot as plt
import seaborn as sns

if weather_df.empty:
    print("weather_df is empty. Cannot generate a pie chart for seasonal weather distribution.")
else:
    if 'Season' in weather_df.columns:
        seasonal_counts = weather_df['Season'].value_counts()
        plt.figure(figsize=(8, 8))
        plt.pie(seasonal_counts, labels=seasonal_counts.index, autopct='%1.1f%%', startangle=140)
        plt.title('Seasonal Weather Distribution')
        plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
        plt.legend(title="Seasons")
        plt.show()
    else:
        print("The 'Season' column is not found in weather_df. Please ensure seasons are derived from date columns first.")

weather_df is empty. Cannot generate a pie chart for seasonal weather distribution.
